### ISSUE TITLE
main.js not getting executed

### ISSUE THREAD

**Issue by ubald** [vazco/meteor-universe-modules-entrypoint#1]
Sorry for being a bit vague for now but maybe it'll ring a bell for you. I started converting my project from modules to modules-entrypoint. At first I got errors all over the place, as expected, but I was still able to have files loaded and executing while fixing the errors. That is until the point where I fixed the last error I had, I had a couple of refreshes that were working, I tested the app and it seemed fine. I then made a change completely unrelated to modules, rebuilt, and then nothing is executing, nothing on the server console, nothing in the browsers console. I put a single console.log in main.js and it never shows. I then try different thing... it sometimes executes and shows the site, I then remove my console.log and it goes back to doing nothing.

Thanks.

**Comment by ubald** [comment]
It might have something to do with universe-modules-compiler though, as my main.js file gets wrapped with: `System.register` instead of `System.autoload`

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
