### ISSUE TITLE
failed to build on linux: [Object object] has no method autoLoad

### ISSUE THREAD

**Issue by ghost** [vazco/meteor-universe-modules-entrypoint#2]
Hello, I'm trying to run test app to understand how module system work in Meteor, working on Centos 7, meteor 1.2.1. Removed ecmascript package and added universe:modules-entrypoint, then run meteor command from terminal and building process end up with error: 

[yukinohito@localhost module-test]$ meteor  
[[[[[ /srv/meteorApps/module-test ]]]]]       

=> Started proxy.  
=> Started MongoDB.  
W20151226-18:50:44.514(2)? (STDERR)  
W20151226-18:50:44.516(2)? (STDERR) /home/yukinohito/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151226-18:50:44.517(2)? (STDERR)                                             throw(ex);
W20151226-18:50:44.517(2)? (STDERR)                                                   ^
W20151226-18:50:44.517(2)? (STDERR) TypeError: Object [object Object] has no method 'autoLoad'
W20151226-18:50:44.517(2)? (STDERR)     at /srv/meteorApps/module-test/.meteor/local/build/programs/server/app/main.js:9:8
W20151226-18:50:44.517(2)? (STDERR)     at main.js:7:4
W20151226-18:50:44.518(2)? (STDERR)     at /srv/meteorApps/module-test/.meteor/local/build/programs/server/boot.js:242:10
W20151226-18:50:44.518(2)? (STDERR)     at Array.forEach (native)
W20151226-18:50:44.518(2)? (STDERR)     at Function._.each._.forEach (/home/yukinohito/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151226-18:50:44.518(2)? (STDERR)     at /srv/meteorApps/module-test/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
